City-of-Helsinki/kukkuu-admin

src/App.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/mock_data.js
src/venues/VenueList.tsx

We use mock data for now to get something visible until the actual API
integration is implemented.

KK-241 | Add initial venue list

---

.env
.gitlab-ci.yml
package.json
src/index.tsx
yarn.lock

I used the same setup as in kukkuu-ui

KK-293 | Add Sentry to project

---

public/index.html
public/manifest.json
public/robots.txt

* Changing html language to fi since most administrators will use the panel in Finnish
* Blocking robots from finding this admin panel

Improve html meta tags and block robots

---

src/api/dataProvider.ts
src/api/generatedTypes/AddVenue.ts
src/api/generatedTypes/Event.ts
src/api/generatedTypes/Events.ts
src/api/generatedTypes/UpdateVenue.ts
src/api/generatedTypes/Venue.ts
src/api/generatedTypes/Venues.ts
src/api/generatedTypes/globalTypes.ts
src/api/utils/apiUtils.ts
src/common/components/languageTab/LanguageTabs.tsx
src/common/translation/en.json
src/common/translation/fi.json
src/common/translation/sv.json
src/domain/application/App.tsx
src/domain/events/detail/EventShow.tsx
src/domain/venues/VenueCreate.tsx
src/domain/venues/VenueEdit.tsx
src/domain/venues/VenueShow.tsx
src/domain/venues/api/VenueApi.ts
src/domain/venues/api/mutations/venueMutations.ts
src/domain/venues/validations.ts

Implemented initial views for creating new events and editing existing ones.

KK-235 | Venue create and edit views

---

src/api/dataProvider.ts
src/api/generatedTypes/AddEvent.ts
src/api/generatedTypes/UpdateVenue.ts
src/api/generatedTypes/globalTypes.ts
src/common/translation/en.json
src/common/translation/fi.json
src/common/translation/sv.json
src/domain/application/App.tsx
src/domain/events/api/EventApi.ts
src/domain/events/create/EventCreate.tsx
src/domain/events/mutations/EventMutations.ts
src/domain/events/types/EventTypes.ts

* Image uploading still missing
* No style / layout related changes, everything looks default
* There seems to be some kind of caching issue related to the list
view. After creating a new event, one needs to reload the page to get
the new event to appear in the list.
But hey, it works! (just make sure you have [this commit](https://github.com/City-of-Helsinki/kukkuu/pull/108/commits/973f189de4b285193fe4cd4e361a4455356ceb75) in the backend)

KK-217 | Add initial event create implementation

---

src/api/dataProvider.ts
src/api/generatedTypes/UpdateEvent.ts
src/api/generatedTypes/globalTypes.ts
src/common/translation/en.json
src/common/translation/fi.json
src/common/translation/sv.json
src/domain/application/App.tsx
src/domain/events/api/EventApi.ts
src/domain/events/create/EventCreate.tsx
src/domain/events/edit/EventEdit.tsx
src/domain/events/mutations/EventMutations.ts
src/domain/events/queries/EventQueries.ts
src/domain/events/validations.ts
src/domain/venues/VenueEdit.tsx

Edit has pretty much the same form as create, so the stuff from https://github.com/City-of-Helsinki/kukkuu-admin/pull/21 apply here as well.
The PR contains also a couple of other minor fixes.

KK-408 | Add initial event edit implementation

---

package.json
src/api/dataProvider.ts
src/api/generatedTypes/Child.ts
src/api/generatedTypes/Children.ts
src/api/types.ts
src/common/choices.ts
src/common/components/languageTab/LanguageTabs.tsx
src/common/translation/en.json
src/common/translation/fi.json
src/common/translation/sv.json
src/domain/application/App.tsx
src/domain/children/ChildList.tsx
src/domain/children/ChildShow.tsx
src/domain/children/api/ChildApi.ts
src/domain/children/queries/ChildQueries.ts
src/domain/events/detail/EventShow.tsx
src/domain/occurrences/fields.tsx
yarn.lock

KK-224 | Add initial list and show details views for children

---

src/api/dataProvider.ts
src/api/types.ts
src/common/translation/en.json
src/common/translation/fi.json
src/common/translation/sv.json
src/domain/events/api/EventApi.ts
src/domain/events/detail/EventShow.tsx
src/domain/events/list/EventList.tsx
src/domain/events/mutations/EventMutations.ts
src/domain/events/types/EventTypes.ts

Initial event publishing functionality using default React Admin components.

KK-441 | Event publishing functionality

---

src/api/dataProvider.ts
src/api/generatedTypes/MyAdminProfile.ts
src/api/generatedTypes/Project.ts
src/api/types.ts
src/api/utils/apiUtils.ts
src/common/translation/en.json
src/common/translation/fi.json
src/common/translation/sv.json
src/domain/authentication/authProvider.ts
src/domain/authentication/components/OidcCallback.tsx
src/domain/authentication/components/UnauthorizedPage.tsx
src/domain/dashboard/Dashboard.tsx
src/domain/dashboard/api.ts
src/domain/dashboard/queries.ts
src/domain/events/api/EventApi.ts
src/domain/profile/api.ts
src/domain/profile/queries.ts
src/domain/profile/utils.ts
src/domain/venues/api/VenueApi.ts
src/routes.tsx

Details in the commit messages.

KK-334 & KK-442 | Better project support

---

README.md
package.json
src/common/translation/en.json
src/common/translation/fi.json
src/domain/events/create/EventCreate.tsx
src/domain/events/detail/EventShow.tsx
src/domain/events/edit/EventEdit.tsx
yarn.lock

Note that the last commit only reorders the translations by key - it looks "bigger" than it should be

KK-460 | Import translations from Google spreadsheet

---

Dockerfile
package.json
yarn.lock

Remove superfluous graphql version and types that are not in use

---

src/domain/events/mutations/EventMutations.ts
src/domain/venues/api/VenueApi.ts

Fix event and venue editing that was broken by the delete buttons.

Fix event and venue edit

---

src/common/components/dateTimeTextField/DateTimeTextField.tsx
src/common/components/imageField/ImageUploadField.tsx
src/domain/events/create/EventCreate.tsx
src/domain/events/edit/EventEdit.tsx
src/domain/occurrences/OccurrenceCreate.tsx
src/domain/venues/VenueCreate.tsx
src/domain/venues/VenueEdit.tsx

KK-448 | Improve the form layout

---

src/api/dataProvider.ts
src/api/generatedTypes/Child.ts
src/api/generatedTypes/Children.ts
src/api/generatedTypes/Occurrence.ts
src/api/generatedTypes/Occurrences.ts
src/api/generatedTypes/UpdateEvent.ts
src/api/generatedTypes/deleteOccurrence.ts
src/api/generatedTypes/globalTypes.ts
src/api/generatedTypes/updateOccurrence.ts
src/common/components/dateTimeTextField/DateTimeTextField.tsx
src/domain/application/App.tsx
src/domain/events/detail/EventShow.tsx
src/domain/occurrences/OccurrenceEdit.tsx
src/domain/occurrences/api/OccurrenceApi.ts
src/domain/occurrences/mutations/OccurrenceMutations.ts

Bonus: Show event short description & description on event page

KK-440, KK-464 | Add option to edit and delete event occurrences

---

src/api/generatedTypes/Children.ts
src/api/generatedTypes/Events.ts
src/api/generatedTypes/Occurrences.ts
src/api/generatedTypes/Venues.ts
src/domain/children/api/ChildApi.ts
src/domain/children/queries/ChildQueries.ts
src/domain/events/api/EventApi.ts
src/domain/events/queries/EventQueries.ts
src/domain/occurrences/api/OccurrenceApi.ts
src/domain/occurrences/queries/OccurrenceQueries.ts
src/domain/venues/api/VenueApi.ts
src/domain/venues/query/VenueQueries.ts

Requires backend commit https://github.com/City-of-Helsinki/kukkuu/pull/124/commits/d11a83aa0ba019e3c616ae1a394c2cd5b303721a

KK-457 | Use project filter in children, venue, event and occurrence queries

---

src/domain/application/App.tsx

KK-492 | Change menu item order

---

src/api/dataProvider.ts
src/api/generatedTypes/Occurrence.ts
src/api/generatedTypes/Occurrences.ts
src/common/translation/en.json
src/common/translation/fi.json
src/domain/occurrences/OccurrenceShow.tsx
src/domain/occurrences/api/OccurrenceApi.ts
src/domain/occurrences/mutations/OccurrenceMutations.ts
src/domain/occurrences/queries/OccurrenceQueries.ts

KK-462 | Add possibility to mark enrolments attended

---

CHANGELOG.md
package.json
src/api/generatedTypes/Occurrence.ts
src/api/generatedTypes/OccurrenceFragment.ts
src/api/generatedTypes/Occurrences.ts
src/api/generatedTypes/updateOccurrence.ts
src/common/translation/en.json
src/common/translation/fi.json
src/domain/events/detail/EventShow.tsx
src/domain/occurrences/OccurrenceShow.tsx
src/domain/occurrences/api/OccurrenceApi.ts
src/domain/occurrences/queries/OccurrenceQueries.ts
yarn.lock

Adds the amount of people who are queueing to an event to occurrence list on the event page as well as to occurrence show.
* Also fixes a bug which caused the occurrence show view to return blank when the user hard refreshed the page.
* Also adds placeholder values for enrolments that no longer have a guardian

KK-461 | Add number of people in queu to admin UI

---

CHANGELOG.md
package.json

Some documentation changes have been applied to master but do not yet exist in develop.

Chore | Merge master into develop

---

CHANGELOG.md
package.json

- Occurrence enrollments with no guardians now have placeholder values
- Number of people in queue and enrolled to event occurrence
- Number of people in queue to event page
- Reloading occurrence show field no longer returns a blank page

[develop] Release 1.3.0

---

src/common/translation/fi.json
src/domain/messages/api/messagesApi.ts

Changes the empty value for array fields and adjusts Finnish translation.
These changes address small fixes I've been told about through Slack.
I've tested these changes manually.
As a signed in admin users
1. Select an unsent message which has specified occurrences (create a new one if such a message does not exist)
1. Set occurrences to all
1. Save
1. Refresh
1. Expect occurrences to still be all

Small fixes to messaging

---

CHANGELOG.md
package.json
src/index.tsx

https://github.com/City-of-Helsinki/kukkuu-admin/pull/102

[Develop] Release 1.4.0

---

package.json
yarn.lock

Fixes security warnings yielded by `npm audit`
There should be no breaking changes. I tested against regressions by using the most common views of the UI.

Chore | Fix security warnings

---

README.md

Removes stale information from the readme.

Chore | Update readme

---

.github/workflows/browser-test.yml

Replace third party action with first party implementation.
I forgot to refactor the browser tests when I moved away from using this action.

Chore | Remove third party action

---

src/domain/events/api/EventApi.ts

Fixed event editing which had gone broken at some point during the battle.
[KK-667](https://helsinkisolutionoffice.atlassian.net/browse/KK-667)

KK-667 | Fix event editing

---

CHANGELOG.md
package.json

- [#132](https://github.com/City-of-Helsinki/kukkuu-admin/pull/132) Add project select
- [#130](https://github.com/City-of-Helsinki/kukkuu-admin/pull/130) Use GitHub flow instead of GitFlow
- [#134](https://github.com/City-of-Helsinki/kukkuu-admin/pull/134) Authorization check
- [#134](https://github.com/City-of-Helsinki/kukkuu-admin/pull/134) Unauthorized view styles

Document release 1.5.1

---

CHANGELOG.md
src/common/translation/en.json
src/common/translation/fi.json

Changes title of the application to one that has been agreed upon with the client.
[KK-701](https://helsinkisolutionoffice.atlassian.net/browse/KK-701)
I've tested this manually by running the application.
Open the PR environment
1. Expect the title to read "Kulttuurin kummilapset admin-käyttöliittymä"

KK-701 | Change application title

---

CHANGELOG.md
package.json

- [#154](https://github.com/City-of-Helsinki/kukkuu-admin/pull/154) Production build API URL

Release 1.5.4

---

CHANGELOG.md
src/api/generatedTypes/Child.ts
src/api/generatedTypes/Event.ts
src/api/generatedTypes/EventGroup.ts
src/api/generatedTypes/Message.ts
src/api/generatedTypes/MessageFragment.ts
src/api/generatedTypes/Messages.ts
src/api/generatedTypes/Occurrence.ts
src/api/generatedTypes/OccurrenceFragment.ts
src/api/generatedTypes/Occurrences.ts
src/api/generatedTypes/Project.ts
src/api/generatedTypes/Venue.ts
src/api/generatedTypes/globalTypes.ts
src/domain/occurrences/Guardian.ts
src/domain/occurrences/OccurrenceShow.tsx
src/domain/occurrences/__tests__/OccurrenceShow.test.jsx
src/domain/occurrences/queries/OccurrenceQueries.ts

A couple of enhancements to occurrence view enrolments list:
* Added guardian phone number
* Fixed row clicking, it will take the user to the child's details view
[KK-756](https://helsinkisolutionoffice.atlassian.net/browse/<KK-756>)
[KK-816](https://helsinkisolutionoffice.atlassian.net/browse/<KK-816>)

KK-756 & KK-816 | Occurrence show view enrolments list enhancements

---

src/common/translation/fi.json

Adjust naming for enrolment count column.
[KK-923](https://helsinkisolutionoffice.atlassian.net/browse/KK-923)

KK-923 | Fix enrolment count label

---

src/api/generatedTypes/ImportTicketSystemPasswordsMutation.ts
src/api/generatedTypes/globalTypes.ts
src/common/translation/en.json
src/common/translation/fi.json
src/domain/events/detail/EventShow.tsx
src/domain/ticketSystemPassword/ImportTicketSystemPasswordsFormDialog.tsx
src/domain/ticketSystemPassword/api/ticketSystemPasswordsApi.ts
src/domain/ticketSystemPassword/mutations/TicketSystemPasswordMutations.ts

Import event passwords dialog

---

src/api/generatedTypes/AddEvent.ts
src/api/generatedTypes/Event.ts
src/api/generatedTypes/Events.ts
src/api/generatedTypes/UpdateEvent.ts
src/api/generatedTypes/globalTypes.ts
src/common/translation/en.json
src/common/translation/fi.json
src/domain/events/__tests__/validations.test.ts
src/domain/events/api/EventApi.ts
src/domain/events/create/EventCreate.tsx
src/domain/events/detail/EventShow.tsx
src/domain/events/edit/EventEdit.tsx
src/domain/events/mutations/EventMutations.ts
src/domain/events/queries/EventQueries.ts
src/domain/events/validations.ts
src/domain/occurrences/OccurrenceCreate.tsx
src/domain/occurrences/OccurrenceEdit.tsx
src/domain/occurrences/api/OccurrenceApi.ts
src/domain/occurrences/inputs.tsx
src/domain/occurrences/queries/OccurrenceQueries.ts
src/domain/ticketSystemPassword/ImportTicketSystemPasswordsFormDialog.tsx

Added external ticket system (=Ticketmaster ATM) URL field to events and removed it from occurrences.
[KK-963](https://helsinkisolutionoffice.atlassian.net/browse/KK-963)

KK-963 | Add event related external ticket system URL field

---

src/api/generatedTypes/AddEvent.ts
src/api/generatedTypes/Event.ts
src/api/generatedTypes/Events.ts
src/api/generatedTypes/Occurrence.ts
src/api/generatedTypes/Occurrences.ts
src/api/generatedTypes/UpdateEvent.ts
src/api/generatedTypes/globalTypes.ts
src/domain/events/detail/EventShow.tsx
src/domain/occurrences/OccurrenceShow.tsx
src/domain/occurrences/fields/OccurrenceAttendedField.tsx
src/domain/occurrences/queries/OccurrenceQueries.ts

Started using new count fields in occurrences query to speed it up.
**Requires https://github.com/City-of-Helsinki/kukkuu/pull/306**
[KK-976](https://helsinkisolutionoffice.atlassian.net/browse/KK-976)

KK-976 | Improve occurrences tab performance

---

.github/workflows/devops_review_tunnistamo.yml
azure-pipelines-review.yml
package.json

[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)

Devops review pipelines

---

src/api/dataProvider.ts
src/domain/children/ChildList.tsx

KK-1049. 
- The Child component should not get any props as an argument
- Use some generics to clean the dataprovider.
The actual fix to this pagination issue should be included in the API change https://github.com/City-of-Helsinki/kukkuu/pull/332.

Cleaning related tot data provider and Child component

---

README.md
package.json
src/domain/children/ChildList.tsx
src/domain/children/ChildShow.tsx
src/domain/occurrences/Occurrence.ts
src/domain/occurrences/OccurrenceShow.tsx

Sonarcloud fixes to KK-1076
[KK-1076](https://helsinkisolutionoffice.atlassian.net/browse/KK-1076)
[KK-1076]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Sonarcloud fixes to KK-1076

---

package.json
src/domain/application/layout/kukkuuListPage/KukkuuListPage.tsx
src/domain/eventsAndEventGroups/list/Empty.tsx
src/domain/eventsAndEventGroups/list/EventsAndEventGroupsList.tsx
src/domain/eventsAndEventGroups/list/ManagementButtonGroup.tsx
src/domain/eventsAndEventGroups/list/empty.module.css
yarn.lock

KK-1081
When the proejct does not allow single event creation and the user has no permissions to create event groups:
With permissions to create only events:
With permissions to create events and event groups:
When the list is not empty, the toolbar appears:

Events and events groups empty listing did not render any management buttons

---

src/domain/application/__tests__/__snapshots__/App.test.tsx.snap

test: update failing snapshot

---

README.md
package.json
yarn.lock

refs KK-1043
[KK-1043](https://helsinkisolutionoffice.atlassian.net/browse/KK-1043)
[KK-1043]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1043 | refactor: remove "update-translations" script & helsinki-utils package

---

README.md
src/common/utils.ts

docs: remove create_superuser env-variable

---

src/domain/api/generatedTypes/graphql.tsx

KK-1128.
Ran `yarn graphql:generate` against the latest changes of Kukkuu API.

fix: update graphql schema

---

src/api/dataProvider.ts
src/api/types.ts
src/domain/authentication/CallbackPage.tsx
src/domain/authentication/authService.ts
src/domain/authentication/authorizationService.ts
src/domain/profile/ProfileProjectDropdown.tsx
src/domain/projects/projectService.ts

KK-1197.
A default project should not be set as an active by an auth renewal process
when a project is already selected.

Authorization renewal process should not reset a selected project

---

src/domain/api/generatedTypes/graphql.tsx

KK-1108
Schema update after django-graphene upgrade in the API.
Fullfills the https://github.com/City-of-Helsinki/kukkuu/pull/390/

fix: update the graphql schema

---

src/domain/messages/detail/MessageDetailsToolbar.tsx

refs KK-1213
[KK-1213](https://helsinkisolutionoffice.atlassian.net/browse/KK-1213)
[KK-1213]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1213 | feat: add working delete button to unsent message's detail page

---

src/domain/application/AppConfig.ts

fix: the oidc silent token renew should e enabled by default

---

.env.example
.env.local.example
src/domain/api/generatedTypes/graphql.tsx
src/domain/messages/api/messagesApi.ts
src/domain/messages/list/MessagesList.tsx
src/domain/messages/queries/MessageQueries.ts

KK-1214.
Dependency to API changes in https://github.com/City-of-Helsinki/kukkuu/pull/413.

Add pagination to messages list

---

src/common/translation/en.json
src/common/translation/fi.json
src/common/translation/sv.json
src/domain/api/generatedTypes/graphql.tsx
src/domain/events/choices.ts
src/domain/events/mutations/EventMutations.ts
src/domain/events/queries/EventQueries.ts
src/domain/occurrences/mutations/OccurrenceMutations.ts

KK-1215 KK-1219.
Add the Tixly external ticket system next to Ticketmaster and Lippupiste. The implementation is the same between the all 3 of them.

feat: add tixly ticket system

---

.github/PULL_REQUEST_TEMPLATE.md
.husky/commit-msg
.husky/pre-commit
.lintstagedrc.json
CHANGELOG.md
README.md
commitlint.config.cjs
package.json
src/assets/styles/index.css
yarn.lock

KK-1347.
The Git commits should be linted and the code changes should be tested
before the commit is committed.
- Installed Husky as a pre commit tool.
- Installed commitlint as a tool to check the conventional commit
format.
- Installed lint-staged as a tool to gather the staged git files.
Used this as a guide:
https://theodorusclarence.com/shorts/husky-commitlint-prettier.

chore: install and init husky and commitlint

---

yarn.lock

Run "yarn upgrade" to upgrade yarn.lock versions
[KK-1356](https://helsinkisolutionoffice.atlassian.net/browse/KK-1356)
[KK-1356]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1356 | chore: run "yarn upgrade" to upgrade yarn.lock versions

---

README.md

KK-1379.
1. Document git commit hooks and husky.
2. Document releases, deploying and release-please.

Document git commit hooks and deployments

---

src/common/components/dateTimeTextField/DateTimeTextField.tsx
src/domain/config.ts
src/domain/eventGroups/detail/EventGroupsDetailActions.tsx
src/domain/eventsAndEventGroups/list/ManagementButtonGroup.tsx
src/domain/occurrences/api/OccurrenceApi.ts

KK-1399.
The helper text gave only 1 format, which did not match any of the actual validation formats.

fix: occurrence date time validation

---

compose.yaml

chore: docker compose production port forward

---

index.html

feat: add csp meta-tag

---

src/domain/application/App.tsx

KK-1407.
See more: https://marmelab.com/react-admin/Admin.html#disabletelemetry.

fix: disable React-admin telemetry

---

index.html

fix: add blob to img-src CSP-rule

---

src/common/components/publishedField/PublishedField.tsx
src/common/utils.ts
src/domain/children/ChildShow.tsx
src/domain/events/detail/EventShow.tsx
src/domain/events/fields.tsx
src/domain/occurrences/OccurrenceShow.tsx

Fixed date and date time formatting of date fields.

fix: date formats of date fields

---

src/domain/authentication/authService.ts

fix: convert ms to seconds for UserManager

---

src/common/components/confirmMutationButton/ConfirmMutationButton.tsx

Fix the sole SonarCloud reliability issue in kukkuu-admin. See commit for details.
- [KK-1416](https://helsinkisolutionoffice.atlassian.net/browse/KK-1416)
- [SonarCloud issues](https://sonarcloud.io/summary/overall?id=City-of-Helsinki_kukkuu-admin&branch=master)
[KK-1416]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1416 | Fix SonarCloud reliability issues

---

src/api/apolloClient/handleApolloError.ts
src/domain/authentication/CallbackPage.tsx
src/domain/authentication/__tests__/authService.test.jsx
src/domain/authentication/authService.ts

Fix async issue related to resetAuthState.

fix: authService resetAuthState should be asynchronous

---

package.json
yarn.lock

fix(deps): upgrade vitest coverage package

---

vitest.config.ts

chore: test coverage report in text

---

.github/workflows/ci.yml
sonar-project.properties

* CI workflow with reusable template
* sonarcloud configuration
[KK-1420](https://helsinkisolutionoffice.atlassian.net/browse/KK-1420)
[KK-1420]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: ci workflow

---

src/domain/dashboard/__tests__/Dashboard.test.jsx
src/domain/occurrences/fields/OccurrenceAttendedField.tsx
src/domain/occurrences/fields/__tests__/OccurrenceAttendedField.test.jsx
src/domain/occurrences/fields/__tests__/OccurrenceTimeRangeField.test.jsx

KK-1420
- OccurrenceTimeRangeField
- OccurrenceAttendedField

test: improve test coverage

---

.github/workflows/ci.yml

[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)

chore: ci reusable workflow branch to main

---

.github/workflows/ci.yml
.github/workflows/release-please.yml
pipelines/kukkuu-admin-dev.yml
pipelines/kukkuu-admin-review.yml

Refs: [KK-1427](https://helsinkisolutionoffice.atlassian.net/browse/KK-1427)
[KK-1427]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: default branch name change
