Dockerfile
Previously the build time environment variables from the GitLab
pipeline config didn't reach the container properly.
=> Fix Docker environment variable passing

package.json, src/api/dataProvider.ts, src/api/generatedTypes/Event.ts, src/api/generatedTypes/Events.ts, src/api/generatedTypes/Occurrences.ts, src/api/generatedTypes/addOccurrence.ts, src/api/generatedTypes/globalTypes.ts, src/api/types.ts, src/common/translation/en.json, src/common/translation/fi.json, src/common/translation/sv.json, src/domain/application/App.tsx, src/domain/events/detail/EventShow.tsx, src/domain/occurrences/OccurrenceCreate.tsx, src/domain/occurrences/api/OccurrenceApi.ts, src/domain/occurrences/mutations/OccurrenceMutations.ts, src/domain/occurrences/queries/OccurrenceQueries.ts, yarn.lock
Known issues:
* ATM uses browser default datetime picker which is pretty horrid
* has [the same caching(?) issue](https://helsinkisolutionoffice.atlassian.net/browse/KK-407) as events and venues where you need reload the app after creating a new instance
=> KK-226 & KK-229 | List and create event occurrences

src/api/dataProvider.ts, src/api/generatedTypes/Occurrence.ts, src/api/generatedTypes/Occurrences.ts, src/common/translation/en.json, src/common/translation/fi.json, src/common/translation/sv.json, src/domain/application/App.tsx, src/domain/children/ChildShow.tsx, src/domain/children/api/ChildApi.ts, src/domain/events/detail/EventShow.tsx, src/domain/occurrences/OccurrenceCreate.tsx, src/domain/occurrences/OccurrenceShow.tsx, src/domain/occurrences/api/OccurrenceApi.ts, src/domain/occurrences/queries/OccurrenceQueries.ts
Known issue: for some reason occurrence details page urls don't work,
so refreshing the app while viewing occurrence details will result in
a blank page. Also, perhaps for the same reason, clicking an occurrence
in child details page's occurrence list will result in the same blank
page.
=> KK-230 | Add initial occurrence details page

src/api/dataProvider.ts, src/api/generatedTypes/Venue.ts, src/api/generatedTypes/Venues.ts, src/api/generatedTypes/deleteEvent.ts, src/api/generatedTypes/deleteVenue.ts, src/api/generatedTypes/globalTypes.ts, src/domain/children/ChildList.tsx, src/domain/events/api/EventApi.ts, src/domain/events/edit/EventEdit.tsx, src/domain/events/list/EventList.tsx, src/domain/events/mutations/EventMutations.ts, src/domain/venues/VenueEdit.tsx, src/domain/venues/VenueList.tsx, src/domain/venues/api/VenueApi.ts, src/domain/venues/api/mutations/venueMutations.ts, src/domain/venues/query/VenueQueries.ts
* Only venues that have no event occurrences using them can be deleted.
* Only unpublished events can be deleted.
Also disabled bulk delete actions from the UI because those are not implemented.
=> KK-349 & KK-439 | Implement event and venue delete

src/api/generatedTypes/Occurrence.ts, src/api/generatedTypes/Occurrences.ts, src/api/generatedTypes/addOccurrence.ts, src/api/generatedTypes/globalTypes.ts, src/api/generatedTypes/updateOccurrence.ts, src/common/components/sanitizedGrid/SanitizedGrid.tsx, src/common/translation/en.json, src/common/translation/fi.json, src/domain/events/detail/EventShow.tsx, src/domain/occurrences/OccurrenceEdit.tsx, src/domain/occurrences/OccurrenceShow.tsx, src/domain/occurrences/api/OccurrenceApi.ts, src/domain/occurrences/mutations/OccurrenceMutations.ts, src/domain/occurrences/queries/OccurrenceQueries.ts
* Changed occurrence capacity to be read from occurrence `capacity` instead of event `capacityPerOccurrence` when showing occurrence info
* Enabled setting occurrence `capacityOverride` in add and edit views
=> KK-545 | Add occurrence capacityOverride field

src/api/generatedTypes/DeleteMessage.ts, src/api/generatedTypes/Message.ts, src/api/generatedTypes/MessageFragment.ts, src/api/generatedTypes/Messages.ts, src/api/generatedTypes/globalTypes.ts, src/common/translation/en.json, src/common/translation/fi.json, src/common/translation/i18nProvider.tsx, src/common/translation/sv.json, src/domain/messages/api/messagesApi.ts, src/domain/messages/mutations/MessageMutations.ts
Implements the delete call of the messages API. I also adjusted react-admin translations in order to hide the ID of the deleted resource from the modal title.
By adding the delete call to the API we make the delete button in the message view work--it now deleted the message and should redirect users correctly.
[KK-596](https://helsinkisolutionoffice.atlassian.net/browse/KK-596)
This has been tested manually by trying out the delete button.
As a logged in admin user
1. Access message list view
1. Create a new message
1. Select the created message by clicking it from the list
1. Access edit view by pressing the edit button. If details view is not yet implemented, access the view by removing `/ show` from the url.
1. Press delete button
1. Expect deleting to work: no errors
1. Expect to be …
=> KK-596 | Make delete button work

src/common/components/kukkuuCardPageLayout/BreadCrumbs.tsx, src/common/components/kukkuuCardPageLayout/KukkuuCardPageLayout.tsx, src/common/components/kukkuuCreatePage/KukkuuCreatePage.tsx, src/common/components/kukkuuDetailPage/KukkuuDetailPage.tsx, src/common/components/kukkuuEditPage/KukkuuEditPage.tsx, src/common/components/kukkuuListPage/KukkuuListPage.tsx, src/common/components/kukkuuPageTitle/KukkuuPageTitle.tsx, src/common/components/publishedField/PublishedField.tsx, src/domain/messages/detail/MessagesDetail.tsx, src/domain/messages/edit/MessagesEdit.tsx, src/domain/messages/form/MessageForm.tsx, src/domain/messages/hooks/useLanguageTabs.tsx, src/domain/messages/list/MessagesList.tsx
This PR adds the details view for messages. It adds the `KukkuuCardPageLayout` abstraction, which supports a very basic breadcrumbs setup.
This PR also adjusts the UI in a few minor ways
- The field for event in list view would return empty with no event when the label should be "All Events" if no single event is specified
- Fixes confusing naming for prop `placeholder` of `PublishedField`
- Changes the page title from a span element into a H1 element
This change is done in order to support manual message management through this admin UI.
[KK-597](https://helsinkisolutionoffice.atlassian.net/browse/KK-597)
This has been tested manually.
As a logged in admin user
1. Access messages view from the left navigation menu
1. Select message from list by clicking
1. Expect to be taken into the …
=> KK-597 | Add message details view

src/api/client.ts
In this PR I stop permission related errors from being sent into Sentry. I also improve the way in which GraphQL errors are sent into Sentry. Previously they were sent using the `captureException` method, but that methods officially only supports `Error` objects. Instead I am now using the `captureMessage` method, and pass the other additional information using Sentry's context.
Kukkuu admin's Sentry is filled with permission related errors that happen when authentication expires or when the user has not yet authenticated at all. In these instances a permission error is an expected conclusion.
I've logged test events into Sentry and checked that the additional context is communicated as expected as well as that permission related errors are now ignores.
I logged test events into our …
=> Do not send permission errors to Sentry

.env, .env.example, .gitignore, .testcaferc.json, .travis.yml, CHANGELOG.md, README.md, browser-tests/messageFeature.ts, browser-tests/pages/login.ts, browser-tests/pages/messages.ts, browser-tests/pages/navigation.ts, browser-tests/pages/routes.ts, browser-tests/pages/ssoLogin.ts, browser-tests/utils/login.ts, browser-tests/utils/settings.ts, browser-tests/utils/valueUtils.ts, package.json, yarn.lock
In this PR I am adding browser based tests for the messaging feature.
Because this feature is close to being finished, I have added happy path tests that take inspiration from the user story.
I don't actually send the message in any of these tests, because sent messages can't be deleted.
I've configured a custom project for these test to run in, in order to have better assurances that the test data is not tampered with by accident.
[KK-580](https://helsinkisolutionoffice.atlassian.net/browse/KK-580)
This PR contains one fixture with two happy path tests. I've tested that they work locally as well as against the test version of kukkuu admin.
Ensure that your environment provides access to the required variables:
- `BROWSER_TESTS_UID`
- `BROWSER_TESTS_PWD`
These can be found from the …
=> KK-580 | Add browser tests for messages feature

browser-tests/utils/valueUtils.ts, src/api/dataProvider.ts, src/api/generatedTypes/Message.ts, src/api/generatedTypes/MessageFragment.ts, src/api/generatedTypes/Messages.ts, src/common/translation/en.json, src/common/translation/fi.json, src/common/utils.ts, src/domain/events/eventSelect/EventSelect.tsx, src/domain/messages/api/messagesApi.ts, src/domain/messages/detail/MessagesDetail.tsx, src/domain/messages/form/MessageForm.tsx, src/domain/messages/form/messageForm.module.css, src/domain/messages/list/MessagesList.tsx, src/domain/messages/queries/MessageQueries.ts, src/domain/occurrences/OccurrenceArraySelect.tsx, src/domain/occurrences/api/OccurrenceApi.ts
Adds ability for users to create messages with occurrences, to edit occurrences in messages, to see selected occurrences in detail view and to select number of occurrences in list view.
I had to implement a bit of custom logic into the `ArraySelectInput` for an occurrence, because I wasn't able to find a way to add an "all" value through the default API.
As an unrelated change in this PR, I cleaned up the implementation of `EventSelect` in order to change it to be more in line with the API of react-admin.
Filtering based on occurrence allows user to target visitors spanning a specific time for instance.
[KK-610](https://helsinkisolutionoffice.atlassian.net/browse/KK-610)
I modified the browsers tests to check that the occurrence count is shown in the list view.
As a logged in admin user …
=> KK-610 | Add support for occurrence filtering in messages

src/domain/events/eventSelect/EventSelect.tsx
This error does not stop the form from submitting.
It seems that react-admin will always yield a missing reference error
when the selected value does not equal an id of one of the records. I'm
not sure whether this is a bug or whether we are using the component in
an unsupported way. For now I have implemented a cheap fix that hides
errors for the empty value.
Without this change users will see an error when they select the all events option.
I have tested this manually.
As a logged in admin level user in the create messages view
1. Choose an event
1. Choose all events
1. Click on title
1. Expect to see no error in the event select field
=> Ignore missing reference error

src/common/translation/en.json, src/common/translation/fi.json, src/domain/messages/detail/MessageSendButton.tsx, src/domain/messages/detail/MessagesDetail.tsx, src/domain/messages/fields/MessageRecipientCountField.tsx
Adds the recipient count to message details view when the message is unsent.
Also adds the recipient count into the confirmation modal before the message is sent.
Users can use the count of recipients as guidance about whether they have configured their recipients correctly.
[KK-635](https://helsinkisolutionoffice.atlassian.net/browse/KK-635)
This has been tested manually by checking that these values are visible.
1. Navigate into an unsent message
1. Expect to see recipient count in the details view
1. Click on "Send"
1. Expect confirmation window to show recipient count
=> KK-635 | Show recipient count in message details view

package.json, src/domain/messages/form/MessageForm.tsx, src/domain/messages/form/__tests__/MessageForm.test.jsx
Some fields do not have any effect depending on the value of another field. This PR tackles these two cases:
* When receivers is set to "All", the event select and occurrence won't be shown
* When receivers is set to "Invited", the occurrence select won't be shown
Moreover, values in these selects are nullified
* If the user selects recipients as "Notified" and then an event, and then selects occurrences, and then selects "All" recipients, the selections for event and occurrences are reset.
* Whenever the user selects an event, the selection for occurrences is reset.
This change makes it easier for the user to understand what combinations are possible.
[KK-636](https://helsinkisolutionoffice.atlassian.net/browse/KK-636)
I added one simple tests, but noticed that it was difficult to mock …
=> KK-636 | Hide recipient filter fields when not relevant

browser-tests/eventsAndEventGrouspFeature.ts, browser-tests/messageFeature.ts, browser-tests/pages/events.ts, browser-tests/pages/navigation.ts, browser-tests/pages/routes.ts, browser-tests/utils/login.ts, src/api/generatedTypes/EventFragment.ts, src/api/generatedTypes/EventsAndEventGroups.ts, src/api/relayList.ts, src/common/translation/en.json, src/common/translation/fi.json, src/domain/application/layout/kukkuuListPage/KukkuuListPage.tsx, src/domain/eventsAndEventGroups/api/eventsAndEventGroupsApi.ts, src/domain/eventsAndEventGroups/list/EventsAndEventGroupsList.tsx, src/domain/eventsAndEventGroups/queries/EventsAndEventGroupsQueries.ts
integrates the UI to the new API, which allows events and events groups to be shown on the same list.
[KK-644](https://helsinkisolutionoffice.atlassian.net/browse/KK-644)
I've added a browser test that checks that it can find at least one event group within the events and events groups list.
1. Navigate to the events view
1. Expect to see events and event groups
1. Expect data columns to behave expectedly
1. Expect clicking event group to take you to the event group view and clicking on an event to take you to the event view
1. Expect correct columns to be highlighted with bold
=> KK-644 | Add event groups to event list

CHANGELOG.md, browser-tests/eventsAndEventGrouspFeature.ts, browser-tests/pages/eventGroups.ts, browser-tests/pages/events.ts, src/api/generatedTypes/EventGroup.ts, src/api/generatedTypes/EventGroupEventFragment.ts, src/common/__tests__/utils.test.js, src/common/components/localDataGrid/LocalDataGrid.tsx, src/common/translation/en.json, src/common/translation/fi.json, src/common/utils.ts, src/domain/eventGroups/api/eventGroupsApi.ts, src/domain/eventGroups/detail/EventGroupsDetail.tsx, src/domain/eventGroups/queries/EvenGroupQueries.ts, src/domain/events/__tests__/utils.test.js, src/domain/events/utils.ts, src/domain/eventsAndEventGroups/list/EventsAndEventGroupsList.tsx
Implements the event group detail view. The API is now integrated into the actual API and the event list displays the correct fields.
[KK-634](https://helsinkisolutionoffice.atlassian.net/browse/KK-634)
I've added some unit tests for utils and an e2e tests for the story this task is developed for.
1. Navigate to some event group (from the event list)
1. Expect to see the expected fields (name, participants per invite, duration, capacity, occurrence count, enrolment count)
1. Expect to see events that belong to that event group
=> KK-634 | Add event group details view

CHANGELOG.md, browser-tests/eventGroupsFeature.ts, browser-tests/pages/eventGroups.ts, browser-tests/pages/events.ts, browser-tests/pages/select.ts, src/domain/eventGroups/detail/EventGroupsDetail.tsx, src/domain/events/create/EventCreate.tsx, src/routes.tsx
Refactors the event group creation view so that if an `eventGroupId` is passed to it in query parameters, it will add the created event into the event group of that id and redirect the user to that event group after the event has been created.
This PR also fixes the browser tests that I accidentally broke with a rename in some earlier commit.
[KK-632](https://helsinkisolutionoffice.atlassian.net/browse/KK-632)
I've added a browser test that test the happy path of the user story.
1. Go to the details of some event group
1. Press the add event button
1. Fill the event form and submit it
1. Expect to be redirected back to the event group
1. Expect to see the created event in the list of events for the event group
=> KK-632 | Add view for adding events into event group

CHANGELOG.md, package.json, src/api/generatedTypes/Occurrence.ts, src/api/generatedTypes/OccurrenceFragment.ts, src/api/generatedTypes/Occurrences.ts, src/common/__tests__/__snapshots__/utils.test.js.snap, src/common/__tests__/utils.test.js, src/common/utils.ts, src/domain/application/layout/kukkuuDetailPage/KukkuuDetailPage.tsx, src/domain/application/layout/kukkuuPageLayout/KukkuuPageLayout.tsx, src/domain/children/ChildShow.tsx, src/domain/events/detail/EventShow.tsx, src/domain/eventsAndEventGroups/list/EventsAndEventGroupsList.tsx, src/domain/messages/detail/MessagesDetail.tsx, src/domain/messages/list/MessagesList.tsx, src/domain/occurrences/Occurrence.ts, src/domain/occurrences/OccurrenceArraySelect.tsx, src/domain/occurrences/OccurrenceShow.tsx, src/domain/occurrences/fields.tsx, src/domain/occurrences/queries/OccurrenceQueries.ts, yarn.lock
I hadn't noticed that the breadcrumb was supposed to work in the Occurrence detail view as well. This PR implements breadcrumbs in the occurrence details view
[KK-616](https://helsinkisolutionoffice.atlassian.net/browse/KK-616)
This has been tested manually. I've checked that occurrences with and without an event group appear correct.
1. Select event grouo
1. Select event
1. Select occurrence
1. Expect to see a breadcrumb
=> KK-616 | Add breadcrumb to occurrence detail view

browser-tests/eventFeature.ts, browser-tests/eventGroupsFeature.ts, browser-tests/messageFeature.ts, browser-tests/pages/events.ts
Browser tests were failing in the CI. I think this was due to two reasons. First, load times are a tad bit longer in the CI environment. This caused the `editButton` in the event details view to be clicked before the event had loaded. The edit button uses the event record for obtaining the `id` of the event. Without the record, it would redirect to an event that did not exist, leading to a failure in the test.
Further, the deletion procedure would fail in the CI. The event model uses the "undo" pattern for deleting events. With react-admin, this works like so:
* user clicks delete
* the model is deleted from the state of the application, but no delete request is sent
* the user has 4s to click "undo" in which case the delete request would be stopped from executing
* unless the user …
=> Chore | Fix browser test

src/domain/events/detail/EventShow.tsx, src/domain/events/types/EventTypes.ts
The publish button for events under an event group should be hidden, because they should be published by using the event group.
[KK-615](https://helsinkisolutionoffice.atlassian.net/browse/KK-615)
I've tested this manually.
1. Select event group
1. Select event
1. Expect to not see a publish button
1. Select a "loose" event
1. Expect to see a publish button
=> KK-615 | Hide event publish button under event group

README.md, src/api/dataProvider.ts, src/api/types.ts, src/common/translation/en.json, src/common/translation/fi.json, src/domain/__tests__/config.test.js, src/domain/config.ts, src/domain/events/api/EventApi.ts, src/domain/events/detail/EventShow.tsx
Implements a button that can be used to mark an event as ready for publishing. Hides the button for now with a feature flag because it isn't yet integrated with the API.
[KK-673](https://helsinkisolutionoffice.atlassian.net/browse/KK-673)
I'll cover this behaviour with an end to end test once the API is ready.
As a logged in user with `REACT_APP_ENABLE_EVENT_READY_TICK` set as turthy in my environment
1. Select event list
1. Select event group
1. Select event
1. Expect to be toggle for marking the event as ready
1. Select a "loose" event
1. Expect to not see a toggle ready button
=> KK-673 | Add a button for setting an event as ready

README.md, src/common/components/localDataGrid/LocalDataGrid.tsx, src/common/translation/en.json, src/common/translation/fi.json, src/domain/__tests__/config.test.js, src/domain/config.ts, src/domain/eventGroups/detail/EventGroupsDetail.tsx, src/domain/eventGroups/detail/EventGroupsDetailActions.tsx, src/domain/eventGroups/detail/EventReadyField.tsx, src/domain/eventGroups/detail/__tests__/EventGroupsDetailActions.test.jsx, src/domain/eventGroups/detail/__tests__/EventReadyField.test.jsx, src/domain/events/detail/EventPublishButton.tsx, src/domain/events/detail/EventReadyToggle.tsx, src/domain/events/detail/EventShow.tsx, src/domain/events/detail/EventShowActions.tsx, src/domain/events/detail/__tests__/EventShowActions.test.jsx
Adds a status label in event group event list which shows whether the event is ready for publishing. The feature is not yet connected to the API, so it doesn't work, but it should be easy to connect to the API once the API is provided for.
As chores I also refactored some event and event group views so that they would be easier to test without having to mock the API.
[KK-674](https://helsinkisolutionoffice.atlassian.net/browse/KK-674)
I've added unit/integration level tests for UI components.
As a logged in user with `REACT_APP_ENABLE_EVENT_READY_FEATURE` set as true in the environment
1. Open event list
1. Select event group
1. Expect to see a "Status" column and for it to contain a pencil icon
=> KK-674 | Add status label to event list under event group

src/common/components/localDataGrid/LocalDataGrid.tsx, src/common/components/localDataGrid/__tests__/LocalDataGrid.test.js
The LocalDataGrid received a non-component child, which caused an error in the rendering logic. I broke this view in https://github.com/City-of-Helsinki/kukkuu-admin/pull/122
When the environment variable `REACT_APP_ENABLE_EVENT_READY_FEATURE` is toggled off, the `LocalDataGrid` component received a child that was falsy instead of a component as it expected.
[KK-674](https://helsinkisolutionoffice.atlassian.net/browse/KK-674)
I added a unit level test that checks that the `LocalDataGrid` can handle falsy values.
As a logged in admin user
1. Select an event group
1. Expect view to not crash
=> Chore | Fix event group details throwing an error

src/domain/occurrences/Occurrence.ts, src/domain/occurrences/__tests__/Occurrence.test.js
Changes the rendering logic for end time to render an empty string instead of null when `occurrence.event.duration` is missing.
[KK-678](https://helsinkisolutionoffice.atlassian.net/browse/KK-678)
I've updated and added a test case.
1. Select an event without a duration
1. Select occurrence tab
1. Expect to not see "null"
=> KK-678 | Fix occurrence end time being rendered as null

CHANGELOG.md, README.md, src/api/generatedTypes/Event.ts, src/api/generatedTypes/EventGroup.ts, src/api/generatedTypes/EventGroupEventFragment.ts, src/api/generatedTypes/UpdateEvent.ts, src/api/generatedTypes/globalTypes.ts, src/common/components/confirmMutationButton/ConfirmMutationButton.tsx, src/common/translation/en.json, src/common/translation/fi.json, src/domain/__tests__/config.test.js, src/domain/config.ts, src/domain/eventGroups/detail/EventGroupsDetail.tsx, src/domain/eventGroups/detail/EventReadyField.tsx, src/domain/eventGroups/detail/PublishEventGroupButton.tsx, src/domain/eventGroups/detail/__tests__/EventReadyField.test.jsx, src/domain/eventGroups/queries/EvenGroupQueries.ts, src/domain/events/api/EventApi.ts, src/domain/events/detail/EventReadyToggle.tsx, src/domain/events/detail/EventShowActions.tsx, src/domain/events/detail/__tests__/EventReadyToggle.test.jsx, src/domain/events/detail/__tests__/EventShowActions.test.jsx, src/domain/events/mutations/EventMutations.ts, src/domain/events/queries/EventQueries.ts, src/domain/events/types/EventTypes.ts
Finalises the functionality implemented partially in previous PRs.
- The publish toggle is only shown for events that belong to an event group and is not yet published
- The publish toggle sends an update mutation which sets the `readyForEventGroupPublishing` field
- The toggle should toggle right away
- The toggle should apply its state based on the result it receives from the server as soon as it's available
- Changes in event's ready state should be reflected in the event group event list view
- If event group publishing fails because some of its events are not published, a special error message is shown
[KK-676](https://helsinkisolutionoffice.atlassian.net/browse/KK-676)
I've added unit tests that cover the new functionality.
1. Access event list
2. Select an …
=> KK-676 | Add ready for publishing button for events in an event group

.gitlab-ci.yml
It seems that there aren't enough resources to have two builds running at the same time because one of the tasks exists with the code 137 which can mean manual kill or an out of memory error. Either there are not enough resources or then maybe the completion of one task exits the other.
The staging version will still be built on master merges. As far as I know it's mostly similar with the staging build. Some configuration does differ.
=> Chore | Don't build production on master merges

.github/workflows/browser-test.yml
I had forgotten to pull in repo secrets into the workflow, which made it fail.
I've manually ran the browser test with the configurations within this branch:
https://github.com/City-of-Helsinki/kukkuu-admin/actions/runs/502979209
=> FIX | Fix browser test env

.github/workflows/review.yml, .github/workflows/staging.yml
Allows usage of Tunnistamo also at review environment(s)
[DEVOPS-227](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-227)
Implemented to open-city-profile-ui, and tested also in created review env manually.
Access review env and sign in.
=> KuVa Tunnistamo to use

CHANGELOG.md, src/common/components/longTextField/LongTextField.tsx
Previously the custom `<LongTextField />` would not show a label. This was due to the logic in `react-admin`'s `SimpleShowLayout` which only wraps those children that have `addLabel` set to `true`.
The fix here was to add `addLabel` as a default prop for `LongTextField`.
[KK-707](https://helsinkisolutionoffice.atlassian.net/browse/KK-707)
I've tested this change manually.
1. Go to venues
2. Select a venue that has all its fields filled
3. Expect all of its fields to have a label
=> KK-707 | Fix LongTextField label in a SimpleShow layout

CHANGELOG.md, src/domain/venues/VenueCreate.tsx
This helper text seems like it has never had a translation. Because it does not have a translation, it makes the UI appear broken.
[KK-709](https://helsinkisolutionoffice.atlassian.net/browse/KK-709)
I've manually checked that the broken helper text is no longer shown.
1. Go to venue creation view
2. Expect to see no broken helper text
=> KK-709 | Remove helper text that does not exist

CHANGELOG.md, browser-tests/pages/events.ts, src/domain/events/edit/EventEdit.tsx
The event editing view seems to have been configured to use the
confirmation pattern, but at some stage the custom edit toolbar has
severed the prop drilling between the form and the delete button. This
resulted in the default pattern, undo, being used instead.
Due to using a custom resource for the event list view, a resource that
contains both events and events groups, react-admin's soft delete
doesn't seem like it works. Instead of hiding the event as soon as
possible, the event is only hidden after the delte request is
completed. By using the confirmation pattern, as was apparently the
original intention, we are able to steer clear of the inefficient undo
logic.
[KK-708](https://helsinkisolutionoffice.atlassian.net/browse/KK-708)
I've tested this manually. I've updated the browser …
=> KK-708 | Fix slowly updating deleted events

CHANGELOG.md, src/domain/events/edit/EventEdit.tsx
The backend expects empty strings instead of null values. By default react-admin sanitizes form values, which transforms empty strings `""` into null.
[KK-706](https://helsinkisolutionoffice.atlassian.net/browse/KK-706)
I've tested this manually by checking that the event edit form no longer returns an error when I attempt to update an event that has a short description to have none.
Access an event with a short description
1. Remove short description
2. Save
3. Expect to see no error message
=> KK-706 | Do not sanitize event editing form

src/domain/eventGroups/edit/EventGroupsEdit.tsx, src/domain/venues/VenueEdit.tsx
In a previous commit I fixed the event editing form, but I did not fix the event group or venue editing forms. In this PR I adjust those forms as well.
These omissions were noted while testing the following ticket
[KK-706](https://helsinkisolutionoffice.atlassian.net/browse/KK-706)
I've tested this manually by removing set values on event group and venue forms.
Access an event group with a short description
1. Remove short description
1. Save
1. Expect to see no error message
Access a venue with an address
1. Remove address
1. Save
1. Expect to see no error message
=> KK-706 | Fix remaining sanitized forms

src/domain/children/ChildShow.tsx, src/domain/venues/VenueShow.tsx
Previously the venue and children views would throw an error relating to the `hasShow` prop. They should no longer do so.
=> Fix hasShow errors

CHANGELOG.md, src/domain/occurrences/Occurrence.ts, src/domain/occurrences/OccurrenceShow.tsx
The occurrence view would previously crash on reload.
[KK-711](https://helsinkisolutionoffice.atlassian.net/browse/KK-711)
I've tested this manually.
2. Select an event with at least a occurrence
3. Go to occurrence tab
4. Select occurrence
5. Reload
6. Expect no error
=> KK-711 | Fix crashing occurrence view

src/api/generatedTypes/Event.ts, src/api/generatedTypes/EventGroup.ts, src/api/generatedTypes/MyAdminProfile.ts, src/api/generatedTypes/Occurrence.ts, src/api/generatedTypes/OccurrenceFragment.ts, src/api/generatedTypes/Occurrences.ts, src/api/generatedTypes/updateOccurrence.ts, src/domain/authentication/__tests__/authProvider.test.js, src/domain/authentication/__tests__/authorizationService.test.js, src/domain/authentication/authProvider.ts, src/domain/authentication/authorizationService.ts, src/domain/eventGroups/detail/EventGroupsDetail.tsx, src/domain/eventGroups/detail/EventGroupsDetailActions.tsx, src/domain/eventGroups/detail/__tests__/EventGroupsDetailActions.test.jsx, src/domain/eventGroups/queries/EvenGroupQueries.ts, src/domain/events/detail/EventShow.tsx, src/domain/events/detail/EventShowActions.tsx, src/domain/events/detail/__tests__/EventShowActions.test.jsx, src/domain/events/queries/EventQueries.ts, src/domain/events/types/EventTypes.ts, src/domain/occurrences/OccurrenceShow.tsx, src/domain/profile/queries.ts
Adjusts the authorizatoin service so that it can be used to check user's permissions on a project per project basis.
Adds checks when rendering event and event group publish buttons which avoids rendering them when the user does not have permission to publish.
[KK-704](https://helsinkisolutionoffice.atlassian.net/browse/KK-704)
I've adjusted the existing tests to cover the changed and new behaviour.
As a user with publish level permissions to a project
1. Navigate to an unpublished event that's not within an event group
2. Expect to see publish button
3. Navigate to an unpublished event group
4. Expect to see publish button
As a user without publish level permissions to a project
1. Navigate to an unpublished event that's not within an event group
2. Expect to not see a publish button
3. …
=> KK-704 | Hide publish buttons when user does not have permissions to publish

src/domain/events/detail/EventShowActions.tsx
After #148 the event details view started to crash after event creation, because the project was accessed before it was available.
[KK-717](https://helsinkisolutionoffice.atlassian.net/browse/KK-717)
1. Create event
2. Expect creation to not lead to an error
=> KK-717 | Fix event details view crashing after event creation

CHANGELOG.md, src/domain/venues/VenueEdit.tsx
Re-entering a venue's edit view after a successful edit would cause a crash.
[KK-710](https://helsinkisolutionoffice.atlassian.net/browse/KK-710)
Reproduction
1. Select venue
2. Change field
3. Edit
4. Expect to be redirected to venue details
5. Re-enter edit view
6. Error
=> KK-710 | Fix crash in venue field after re-entering edit view

CHANGELOG.md, package.json
Changes the translation sheet to one that is managed under the XO's account.
[KK-714](https://helsinkisolutionoffice.atlassian.net/browse/KK-714)
I changed the sheet id and rant he translation script. The script worked and did not cause any changes = I'm happy.
You can try running the script locally. Hit me up if you want to edit the sheet.
=> KK-714 | Change translation sheet to one owned by executive office

CHANGELOG.md, package.json
- [#139](https://github.com/City-of-Helsinki/kukkuu-admin/pull/139) Application title
- [#141](https://github.com/City-of-Helsinki/kukkuu-admin/pull/141) Distinct test environment from production environment
- [#152](https://github.com/City-of-Helsinki/kukkuu-admin/pull/152) Translation sheet to one controlled by the executive office
- [#148](https://github.com/City-of-Helsinki/kukkuu-admin/pull/148) Hide publish button if user does not have permission to publish
- [#142](https://github.com/City-of-Helsinki/kukkuu-admin/pull/142) Missing labels in venue and event detail views
- [#144](https://github.com/City-of-Helsinki/kukkuu-admin/pull/144) Slow update of event and event group list by using confirmation pattern instead of undo pattern when deleting events
- …
=> Release 1.5.3

CHANGELOG.md, src/api/generatedTypes/Project.ts, src/domain/dashboard/queries.ts, src/domain/eventsAndEventGroups/list/EventsAndEventGroupsList.tsx
Hides event creation button in projects which have been configured to not allow loose events.
Uses react-admin's `useQuery` to fetch project data within the event and event group list toolbar component.
[KK-725](https://helsinkisolutionoffice.atlassian.net/browse/KK-725)
I've tested this by hand.
When a project's `singleEventsAllowed` configuration is toggled as false, the user should not be able to create events outside of event groups.
=> KK-725 | Hide event creation button when not supported in project

CHANGELOG.md, src/api/generatedTypes/MyAdminProfile.ts, src/domain/authentication/__tests__/authProvider.test.js, src/domain/authentication/__tests__/authorizationService.test.js, src/domain/authentication/authProvider.ts, src/domain/authentication/authService.ts, src/domain/authentication/authorizationService.ts, src/domain/children/api/ChildApi.ts, src/domain/dashboard/Dashboard.tsx, src/domain/eventGroups/api/eventGroupsApi.ts, src/domain/eventGroups/detail/EventGroupsDetailActions.tsx, src/domain/eventGroups/detail/__tests__/EventGroupsDetailActions.test.jsx, src/domain/events/api/EventApi.ts, src/domain/eventsAndEventGroups/api/eventsAndEventGroupsApi.ts, src/domain/eventsAndEventGroups/list/EventsAndEventGroupsList.tsx, src/domain/messages/api/messagesApi.ts, src/domain/occurrences/api/OccurrenceApi.ts, src/domain/profile/ProfileProjectDropdown.tsx, src/domain/profile/__tests__/ProfileProjectDropdown.test.jsx, src/domain/profile/queries.ts, src/domain/projects/__tests__/profileService.test.js, src/domain/projects/projectService.ts, src/domain/venues/api/VenueApi.ts
Hides the create and edit buttons for users who do not have crud permissions for event groups within a project.
[KK-728](https://helsinkisolutionoffice.atlassian.net/browse/KK-728)
Manually.
Ensure that users are not able to access the CRUD buttons for event groups (create, edit, delete) when they do not have the `Can create, update and delete event groups` permission within the project the event group belongs to.
=> KK-728 | Hide event group create and edit buttons when user does not have permissions for CRUD operations

CHANGELOG.md, src/domain/messages/fields/MessageRecipientCountField.tsx
Removes the default value that was used for 0 recipient counts because zero qualifies as falsy in JS:
[KK-669](https://helsinkisolutionoffice.atlassian.net/browse/KK-669)
=> KK-669 | Fix null recipient count labeled as '?'

CHANGELOG.md, src/domain/events/api/EventApi.ts
Sends an empty string as the value in the image field if no image exists so that the image is cleared.
[KK-685](https://helsinkisolutionoffice.atlassian.net/browse/KK-685)
Images can be removed after they have been saved.
=> KK-685 | Fix unremovable image

CHANGELOG.md, package.json
- [#161](https://github.com/City-of-Helsinki/kukkuu-admin/pull/161) Test label in the login view in the test environment
- [#157](https://github.com/City-of-Helsinki/kukkuu-admin/pull/157) Hide create event button when project does not allow loose events
- [#158](https://github.com/City-of-Helsinki/kukkuu-admin/pull/158) Hide event group create and edit button when the user is not authorized with CRUD permissions
- [#159](https://github.com/City-of-Helsinki/kukkuu-admin/pull/159) Zero recipient count being shown as a question mark
- [#160](https://github.com/City-of-Helsinki/kukkuu-admin/pull/160) Image being unremovable after saving
- [#165](https://github.com/City-of-Helsinki/kukkuu-admin/pull/165) Event editing causing its event group to be nullified
=> Release 1.5.5

README.md
When configuring kukkuu-ui and kukkuu-admin, this should set "Allowed applications" in Tunnistamo as expected.
=> Improve instructions for settings up local Tunnistamo

CHANGELOG.md, src/common/translation/en.json, src/common/translation/fi.json, src/domain/authentication/AuthErrorPage.tsx, src/domain/authentication/CallbackPage.tsx, src/domain/authentication/InfoPageTemplate.tsx, src/domain/authentication/UnauthorizedPage.tsx, src/domain/authentication/authService.ts
I was able to reproduce a login issue once and I tracked it down into this phase of the login routine. With an `undefined` value the login process hangs indefinitely in `/callback`. By providing a default value the user will always have a redirect target.
When I tested this approach against the information in the ticket, it's hard to say whether this is an issue some of the users have faced. If you get stuck on the `/callback` route and refresh, you get logged out (the system attempts to end the login routine again, but none is currently taking place, in which case the system errors and logs the user out in order to create a clean slate for the next attempt). Similarly, using the back button will take you out of the service into the authentication provider (in my case GitHub). The page …
=> KK-783 | Fixed login routine when redirect target is unclear

src/api/__tests__/client.tests.js, src/api/client.ts, src/api/utils/apiUtils.ts
Implemented handling of the backend's new authentication-related error codes. Also while at it, removed duplicate error handling from `handleQuery()` and `handleMutation()` helper functions. Now all error handling happens in the Apollo client's error link.
[KK-814](https://helsinkisolutionoffice.atlassian.net/browse/KK-814>)
=> KK-814 | Use new authentication error codes

src/domain/messages/choices.ts, src/domain/messages/form/MessageForm.tsx, src/domain/messages/form/__tests__/MessageForm.test.jsx
Hide event selection when invited recipients is selected in message creation
[KK-824](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)
=> KK-824 | Hide event selection when invited recipients is selected in message creation

CHANGELOG.md, package.json, src/api/apolloClient/__tests__/client.tests.js, src/api/apolloClient/client.ts, src/api/apolloClient/handleApolloError.ts, src/api/apolloClient/unauthenticatedClient.ts, src/api/generatedTypes/VerifyTicket.ts, src/api/utils/apiUtils.ts, src/common/translation/en.json, src/common/translation/fi.json, src/domain/ticketValidation/OccurrenceCard.tsx, src/domain/ticketValidation/TicketValidationPage.tsx, src/domain/ticketValidation/useVerifyTicketQuery.ts, src/routes.tsx, yarn.lock
Adds a new page into the admin UI: `/check-ticket-validity/:cryptographicallySignedCode`
The `cryptographicallySignedCode` is used to make a query into the backend that returns validity (and some other details) about a ticket.
In case of error, a generic error view gets shown.
[KK-508](https://helsinkisolutionoffice.atlassian.net/browse/KK-508)
=> KK-508 | Add ticket validation view

.eslintrc.json, CHANGELOG.md, browser-tests/messageFeature.ts, browser-tests/pages/messages.ts, browser-tests/utils/valueUtils.ts, package.json, src/api/generatedTypes/Message.ts, src/api/generatedTypes/MessageFragment.ts, src/api/generatedTypes/Messages.ts, src/api/generatedTypes/globalTypes.ts, src/api/types.ts, src/common/hooks/useLanguageTabs.tsx, src/common/translation/en.json, src/common/translation/fi.json, src/domain/application/layout/kukkuuCreatePage/KukkuuCreateToolbar.tsx, src/domain/messages/create/MessagesCreate.tsx, src/domain/messages/detail/MessagesDetail.tsx, src/domain/messages/form/MessageForm.tsx, src/domain/messages/list/MessageListToolbar.tsx, src/domain/messages/list/MessagesList.tsx, src/domain/messages/queries/MessageQueries.ts, src/domain/messages/validations.ts, yarn.lock
Allows SMS type messages to be sent through the UI.
When SMS type messages are created, they are sent immediately. Hence they can't be edited or deleted.
SMS type messages are listed with EMAIL type messages in the messages list.
[KK-846](https://helsinkisolutionoffice.atlassian.net/browse/KK-846)
[KK-846](https://helsinkisolutionoffice.atlassian.net/browse/KK-848)
I've extended E2E tests to cover SMS type messages.
=> KK-846, KK-848 | Add SMS messages

src/common/translation/en.json, src/common/translation/fi.json, src/domain/eventGroups/detail/EventGroupsDetailActions.tsx, src/domain/eventGroups/detail/EventReadyField.tsx, src/domain/eventGroups/detail/PublishEventGroupButton.tsx, src/domain/eventGroups/detail/__tests__/EventGroupsDetailActions.test.jsx, src/domain/eventGroups/detail/__tests__/EventReadyField.test.jsx, src/domain/eventGroups/utils.ts
- Added event group republish features. KK-881 KK-884
- Added the event published status indicator to the EventGroup table. KK-881 KK-886. The green checkmark icon is to indicate the status of ready for publishment. The new blue earth icon is to indicate status of published event.
A new republish button (text) and a new (blue) status indicator for the published events:
=> Event group republish features and status indicators

src/api/generatedTypes/Event.ts, src/common/translation/en.json, src/common/translation/fi.json, src/domain/events/detail/EventShow.tsx, src/domain/events/queries/EventQueries.ts, src/domain/ticketSystemPassword/ImportTicketSystemPasswordsFormDialog.tsx
In the future Ticketmaster events cannot have occurrences, so for them "occurrences" tab is replaced with "passwords" tab which contains the password counts and the import button. The passwords tab contains counts of used and free passwords, and the button to import new passwords.
=> KK-902 && KK-958 | Add passwords tab for Ticketmaster events

src/common/translation/en.json, src/common/translation/fi.json, src/domain/events/api/EventApi.ts, src/domain/events/create/EventCreate.tsx, src/domain/events/detail/EventShow.tsx, src/domain/events/edit/EventEdit.tsx, src/domain/events/mutations/EventMutations.ts, src/domain/events/queries/EventQueries.ts
Added event end time field which is shown and used only with external ticket system events. Also changed event duration field to be used only with external ticket system events.
One browser test is failing but that is an old issue unrelated to this PR.
[KK-972](https://helsinkisolutionoffice.atlassian.net/browse/KK-972)
=> KK-972 | Add ticketmaster event end time

src/domain/occurrences/queries/OccurrenceQueries.ts
Got rid of unneeded extra fields in occurrences queries because they were causing the occurrences tab to be very slow on some production events.
This is only a partial solution to the occurrences tab slowness problem, and further tuning is still needed for the backend and this admin side also.
[KK-976](https://helsinkisolutionoffice.atlassian.net/browse/KK-976)
=> KK-976 | Tune occurrences queries

src/domain/occurrences/queries/OccurrenceQueries.ts
Removed a couple of pointless fields from the occurrences query which were added back there unintentionally in a merge.
=> Improve occurrences query

.prod/nginx.conf.template, Dockerfile, package.json
KK-1002 KK-1046
Read the following environment variables that are set in the pipeline process and set them in the respond of the Nginx /readiness -probe:
- RELEASE
- APP_VERSION
- COMMITHASH
- BUILD_TIME
----
The same change in the Kukkuu UI: https://github.com/City-of-Helsinki/kukkuu-ui/pull/501.
The pipeline changes: https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/6470
=> ci: add version and release information in the (Nginx) readiness probe

src/domain/messages/form/MessageForm.tsx
KK-1054.
When a recipient was changed from some event specific selection to "invited", the event fields were not cleared. Because of that, the validation didn't pass, because it had too many fields filled.
The "invited" option is now handled the same as the "all" when the recipient is changed.
----
Steps to reproduce:
1. Fill the form with some event specific data
2. Change the recipient to "invited" <img width="688" alt="image" src="https://github.com/City-of-Helsinki/kukkuu-admin/assets/389204/f4befa80-8ff0-4902-9046-b3ea1d7fab39">
The result: there should be no validation error anymore.
=> fix(messages): recipient selection validation after change

src/api/utils/apiUtils.ts
LIIKUNTA-594.
The null-values are not accepted by the API when dealing with translation objects.
When a translation object field is cleared, it is stored as null in the form context. With the new utilities, it's easier to transform nulls to empty strings. The tools can be used transform for any value .
Steps to reproduce:
Fill an event form field
Clear the value from the input
Save
Result: Earlier this couldn't be done because the API raised a constraint exception.
=> fix: transform nulls to empty strings when sending data to the API

src/domain/messages/detail/MessageDetailsToolbar.tsx, src/domain/messages/detail/MessageSendButton.tsx
KK-1051.
The email message recipient count was not shown properly in the message sending modal window when there were 0 recipients.
Some of the messages are in a scope of 0 recipients:
When a message sending modal is opened, instead of showing `0`, a `?` was shown instead. Now it's fixed:
If there would be more recipients, it would be shown:
=> fix(messages): recipient count in the send email modal window

src/domain/occurrences/OccurrenceShow.tsx
KK-1080.
The column was broken on occurrence page after birthdate to birthyear changes:
Since all the kids have the same value (same year) in the column, the product owner requested for removal of the column:
=> fix: remove the broken birthyear column from occurrence page

src/common/components/dateTimeTextField/DateTimeTextField.tsx, src/domain/occurrences/OccurrenceCreate.tsx, src/domain/occurrences/OccurrenceEdit.tsx
KK-1049.
The React-admin plugin has a special handling for validation in the useInput-hook. That is there to prevent handling the translations to be handled twice -- once by React-admin and once by the input functions I suppose. To fix the translation of the validation error message, a special handler was needed to be used with the BoundedTextField.
Also, the occurrence edit and create views were broken, because the validation function was set as a property for a ReferenceInput (of React-admin), which no longer has such a property.
=> fix: occurrence creation and edit view

.env.test, .gitignore, src/domain/authentication/__tests__/__snapshots__/authService.test.js.snap, src/domain/authentication/__tests__/authService.test.js, src/domain/authentication/authService.ts, src/domain/authentication/authorizationService.ts, src/setupTests.ts
after this change the tokens will be refreshed automatically before the
refresh token expires even if the user does nothing
also:
- set predictable environment variables for tests using .env.test to
make tests run the same locally and in CI/CD pipeline
refs KK-1156
[KK-1156](https://helsinkisolutionoffice.atlassian.net/browse/KK-1156)
Logged in, left the browser running for over 5 mins, saw that network tab contained token fetching, tried to access resources in admin-UI, was successful → **silent refresh works** ✅
- Check out PR's branch locally
- Put this into `.env`
```
PORT=3001
BROWSER_TESTS_UID=
BROWSER_TESTS_PWD=
BROWSER_TESTS_ENV_URL=http://localhost:3001
REACT_APP_KUKKUU_API_OIDC_SCOPE=https://api.hel.fi/auth/kukkuu
REACT_APP_API_URI=https://kukkuu.api.test.hel.ninja/graphql …
```
=> KK-1156 | Add silent token refreshing with Keycloak

browser-tests/messageFeature.ts, browser-tests/pages/messages.ts, browser-tests/utils/jwt/clientUtils/login.ts, browser-tests/utils/jwt/services.ts, browser-tests/utils/jwt/types.ts, src/common/translation/en.json, src/common/translation/fi.json, src/common/translation/sv.json, src/domain/api/generatedTypes/graphql.tsx, src/domain/authentication/__tests__/authProvider.test.js, src/domain/authentication/__tests__/authService.test.js, src/domain/authentication/authProvider.ts, src/domain/authentication/authorizationService.ts, src/domain/events/api/EventApi.ts, src/domain/messages/choices.ts, src/domain/messages/detail/MessageDetailsToolbar.tsx, src/domain/messages/detail/MessagesDetail.tsx, src/domain/messages/form/MessageForm.tsx, src/domain/messages/queries/MessageQueries.ts, src/domain/messages/validations.ts, src/domain/profile/queries.ts
KK-1039.
A list of recipients in Message form will include the choice "all" only
when the current user has 'canSendToAllInProject' permission (in my
admin profile).
The editing of the message record is prevented by hiding the edit action
buttons, when the message is not for the currently active project or the
message has recipients set to "all" and the current user does not have
permissions to send to "all".
Fixed the recipient selection in messages form, which should be
validated as required.
=> feat: messages can be sent to all only with special permission

browser-tests/utils/jwt/jwt.ts
Fix the Kukkuu Admin UI URL
Instead of
- https://kukkuu-admin-ui.test.hel.ninja/
- https://kukkuu-admin-ui.stage.hel.ninja/
the URLs for the Admin UI are:
- https://kukkuu-admin.test.hel.ninja/
- https://kukkuu-admin.stage.hel.ninja/
=> fix(config): admin ui url

Dockerfile
Enable polling only for Docker development as an alternative to PR #299.
[KK-1367](https://helsinkisolutionoffice.atlassian.net/browse/KK-1367)
Ran "docker compose up --build", opened the UI in web browser, and changed LoginPage.tsx's title text a few times and avot, the text changed in the browser with some delay.
[KK-1367]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KK-1367 | Use polling in docker development to enable hot reload

.dockerignore, .env.example, .env.local.example, Dockerfile, README.md, azure-pipelines-review.yml, compose.override.yaml.example, compose.yaml
Revamp README, requirements, getting started etc.
Following the steps in README's "Getting started" one can:
- Run Kukkuu Admin UI using local Node.js or Docker & Docker compose
- Run the Kukkuu backend locally in Docker or use the public test environment's backend
- Use the public test environments of Helsinki Profile and Keycloak for authentication
- Be able to successfully log in to Kukkuu Admin UI
refs KK-1377
[KK-1377](https://helsinkisolutionoffice.atlassian.net/browse/KK-1377)
Manual testing using the README's "Getting started":
- Using local Node.js & public test environment's backend: ✅
- Using local Node.js & local backend: ✅
- Using Docker & public test environment's backend: ✅
- Using Docker & local backend: ✅
**NOTE**:
- I had an existing test Helsinki Profile profile which I …
=> KK-1377 | Revamp README: requirements, getting started etc

.eslintignore
Update `.eslintignore`: remove `node_modules/*`, add `build/*`.
See commit for details.
- [KK-1410](https://helsinkisolutionoffice.atlassian.net/browse/KK-1410)
- PR #312 
[KK-1410]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KK-1410 | Update .eslintignore: remove node_modules/*, add build/*

index.html
logging in to kukkuu-admin failed because of connect-src CSP rule when
using a local backend, this fixes logging in
refs KK-1407
[KK-1407](https://helsinkisolutionoffice.atlassian.net/browse/KK-1407)
[KK-1407]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KK-1407 | Add `localhost:*`, `127.0.0.1:*` to CSP connect-src to fix local development

src/common/components/dateTimeTextField/DateTimeTextField.tsx, src/domain/occurrences/OccurrenceShow.tsx, src/domain/occurrences/api/OccurrenceApi.ts
Fix validation of the DateTimeTextField when it's disabled.
KK-1423.
Occurrence API normalizeTime -function needs to be able to handle
undefined date and time too. This happens e.g. when the fields are
disabled. The normalization should not be done when the denomarlized
value is not set.
----
Fix a hook usage error.
KK-1423.
When a list of occurrence enrolments was rendered, the console went
crazy by reporting an issue in hook usage. This was because a React
component was used in FunctionField render-property and the hooks were
no longer in root level.
By removing the Function field and rendering the OccurrenceAttendedField
directly, the feature still works and the hook warnings are no longer
raised. A catch is, that the field does not have a label property for
the Material UI grid, but …
=> Fix validation of the DateTimeTextField when it's disabled.

src/common/components/imageField/ImageUploadField.tsx, src/common/translation/en.json, src/common/translation/fi.json, src/common/translation/sv.json
KK-1426.
The image upload process ended in "cannot pickle '_io.BufferedRandom' object" error if a too large image was uploaded. The file upload size is set 1MB in Nginx by default (source:
https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) and to 2,5MB in Django (source:
https://docs.djangoproject.com/en/5.2/ref/settings/#file-upload-max-memory-size and
https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-DATA_UPLOAD_MAX_MEMORY_SIZE). The default for React-Admin's ImageInput was `Infinity` (source: https://marmelab.com/react-admin/ImageInput.html), so it was more than what Nginx and Django could handle. The max size that we want to support in our Web app is 1MB, because larger than that would be bad for user experience (because of  pages' total …
=> fix: set max size to 1MB for image upload
